<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>Omens</AssemblyName><RootNamespace>Omens</RootNamespace></PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.AudioModule"><HintPath>$(ManagedDir)/UnityEngine.AudioModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
