<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>Golf</AssemblyName><RootNamespace>MeadowGolf</RootNamespace></PropertyGroup>
  <ItemGroup><Reference Include="UnityEngine.AnimationModule"><HintPath>$(ManagedDir)/UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference><Reference Include="UnityEngine.AudioModule"><HintPath>$(ManagedDir)/UnityEngine.AudioModule.dll</HintPath><Private>false</Private></Reference><Reference Include="gui_framework"><HintPath>$(ManagedDir)/gui_framework.dll</HintPath><Private>false</Private></Reference></ItemGroup>
</Project>
