using BuildShapes;
using System.Text;

int checks=0;
void Check(bool ok,string message){checks++;if(!ok)throw new Exception(message);}
void Bad(Action action,string message){try{action();}catch(Exception ex)when(ex is ArgumentException||ex is IOException||ex is DecoderFallbackException){checks++;return;}throw new Exception("Accepted "+message);}
SharedPreview Frame(long revision=1,byte tool=5)=>new(){World=42,Revision=revision,Tool=tool,Center=new SharedPoint(10,8,-20)};
SharedStroke Line(int n=2)=>new(){Width=0.065f,ThroughGround=true,Points=Enumerable.Range(0,n).Select(i=>new SharedPoint(i*0.25f,i%3,-i)).ToArray()};
SharedGhost Ghost(string name="wood",int i=0)=>new(){Prefab=name,At=new SharedPoint(i,-i,i/2f),Y=0.6f,W=0.8f};
byte[] Change(byte[] bytes,int offset,byte[] change){var copy=(byte[])bytes.Clone();Array.Copy(change,0,copy,offset,change.Length);return copy;}
void Roundtrip(SharedPreview p){var bytes=SharedPreviewCodec.Encode(p);var q=SharedPreviewCodec.Decode(bytes,42);Check(q.World==p.World&&q.Revision==p.Revision&&q.Tool==p.Tool&&q.Center.Equals(p.Center),"header roundtrip");Check(q.Lines.Count==p.Lines.Count&&q.Pieces.Count==p.Pieces.Count,"counts roundtrip");for(int i=0;i<p.Lines.Count;i++)Check(q.Lines[i].Width==p.Lines[i].Width&&q.Lines[i].ThroughGround==p.Lines[i].ThroughGround&&q.Lines[i].Points.SequenceEqual(p.Lines[i].Points),"stroke roundtrip");for(int i=0;i<p.Pieces.Count;i++){var a=p.Pieces[i];var b=q.Pieces[i];Check(a.Prefab==b.Prefab&&a.At.Equals(b.At)&&a.X==b.X&&a.Y==b.Y&&a.Z==b.Z&&a.W==b.W,"pose roundtrip");}}

var clear=Frame(1,0);Roundtrip(clear);var empty=SharedPreviewCodec.Encode(clear);Check(empty.Length==39,"clear wire length");
var partial=Frame();partial.Lines.Add(Line());Roundtrip(partial);
var single=Frame();single.Lines.Add(Line());single.Pieces.Add(Ghost());Roundtrip(single);
var packet=SharedPreviewCodec.Encode(single);
var large=Frame(99);for(int i=0;i<640;i++)large.Lines.Add(Line(i<87?128:i==87?48:2));for(int i=0;i<2048;i++)large.Pieces.Add(Ghost(("piece_"+(i%256)).PadRight(128,'x'),i));Roundtrip(large);Check(SharedPreviewCodec.Encode(large).Length<=SharedPreviewCodec.MaxBytes,"all simultaneous bounds fit transport");
foreach(byte mode in new byte[]{1,2,3,4,5}){var p=Frame(2,mode);p.Pieces.Add(Ghost("modded_梁"));Roundtrip(p);}
for(int length=0;length<packet.Length;length++)Bad(()=>SharedPreviewCodec.Decode(packet.Take(length).ToArray(),42),"truncated frame "+length);
Bad(()=>SharedPreviewCodec.Decode(packet,43),"wrong world");Bad(()=>SharedPreviewCodec.Decode(packet.Concat(new byte[]{0}).ToArray(),42),"trailing bytes");Bad(()=>SharedPreviewCodec.Decode(new byte[SharedPreviewCodec.MaxBytes+1],42),"oversize payload");
Bad(()=>SharedPreviewCodec.Decode(Change(empty,0,new byte[]{0}),42),"bad magic");Bad(()=>SharedPreviewCodec.Decode(Change(empty,12,BitConverter.GetBytes(0L)),42),"zero revision");Bad(()=>SharedPreviewCodec.Decode(Change(empty,20,new byte[]{6}),42),"unknown tool");
foreach(float invalid in new[]{float.NaN,float.PositiveInfinity,1000000f,-1000000f})Bad(()=>SharedPreviewCodec.Decode(Change(empty,21,BitConverter.GetBytes(invalid)),42),"invalid center");
Bad(()=>SharedPreviewCodec.Decode(Change(empty,33,BitConverter.GetBytes((ushort)257)),42),"prefab count bound");Bad(()=>SharedPreviewCodec.Decode(Change(empty,35,BitConverter.GetBytes((ushort)641)),42),"line count bound");Bad(()=>SharedPreviewCodec.Decode(Change(empty,37,BitConverter.GetBytes((ushort)2049)),42),"piece count bound");
// Single-pose packet layout: name length 35, name 37..40, line 43..73, pose 76..105.
Bad(()=>SharedPreviewCodec.Decode(Change(packet,35,BitConverter.GetBytes((ushort)129)),42),"prefab byte length");Bad(()=>SharedPreviewCodec.Decode(Change(packet,37,new byte[]{0xff}),42),"invalid UTF8");Bad(()=>SharedPreviewCodec.Decode(Change(packet,37,new byte[]{10}),42),"control in prefab name");
Bad(()=>SharedPreviewCodec.Decode(Change(packet,43,BitConverter.GetBytes(float.NaN)),42),"NaN width");Bad(()=>SharedPreviewCodec.Decode(Change(packet,47,new byte[]{2}),42),"nonboolean depth flag");Bad(()=>SharedPreviewCodec.Decode(Change(packet,48,BitConverter.GetBytes((ushort)129)),42),"stroke point bound");Bad(()=>SharedPreviewCodec.Decode(Change(packet,76,BitConverter.GetBytes((ushort)1)),42),"prefab index");Bad(()=>SharedPreviewCodec.Decode(Change(packet,90,new byte[16]),42),"zero quaternion");Bad(()=>SharedPreviewCodec.Decode(Change(packet,102,BitConverter.GetBytes(float.PositiveInfinity)),42),"nonfinite quaternion");Bad(()=>SharedPreviewCodec.Decode(Change(packet,20,new byte[]{0}),42),"nonempty clear packet");
var tooMany=Frame();tooMany.Lines.AddRange(Enumerable.Range(0,97).Select(_=>Line(128)));Bad(()=>SharedPreviewCodec.Encode(tooMany),"aggregate points");tooMany=Frame();tooMany.Pieces.AddRange(Enumerable.Range(0,257).Select(i=>Ghost("p"+i)));Bad(()=>SharedPreviewCodec.Encode(tooMany),"distinct prefabs");tooMany=Frame();tooMany.Pieces.Add(null);Bad(()=>SharedPreviewCodec.Encode(tooMany),"null pose");

var state=new SharedPreviewSet();var peers=new HashSet<long>(Enumerable.Range(1,16).Select(i=>(long)i));Check(state.Accept(1,partial,0),"new outline accepted");Check(!state.Accept(1,Frame(1),4)&&state.Entries[1].Seen==4&&state.Entries[1].Preview==partial,"same revision heartbeat retains exact outline");Check(state.Accept(1,Frame(3),5),"newer draft replaces");Check(!state.Accept(1,Frame(2),10)&&state.Entries[1].Seen==5,"stale data cannot refresh timeout");Check(state.Accept(1,Frame(4,0),6)&&state.Entries.Count==0,"clear removes visuals");Check(!state.Accept(1,Frame(3),7)&&state.Entries.Count==0,"clear tombstone prevents resurrection");Check(!state.Accept(1,Frame(4,0),8),"duplicate clear harmless");Check(!state.Accept(1,Frame(4),8)&&state.Entries.Count==0,"same revision cannot undo explicit clear");Check(state.Accept(1,Frame(5),9),"next draft opens");Check(state.Expire(21,peers).Length==0,"exact lifetime retained");Check(state.Expire(21.1f,peers).SequenceEqual(new[]{1L}),"quiet draft expires");Check(!state.Accept(1,Frame(4),22),"expired state still rejects older data");Check(state.Accept(1,Frame(5),22),"unchanged heartbeat revives expired live draft");Check(state.Accept(1,Frame(6),22),"fresh heartbeat updates expired live draft");Check(state.Expire(22,new HashSet<long>()).SequenceEqual(new[]{1L}),"offline draft cleared immediately");Check(state.Accept(1,Frame(1),23),"rejoin forgets old session tombstone");
for(long i=2;i<=8;i++)Check(state.Accept(i,Frame(),24),"eight active viewers allowed");Check(!state.Accept(9,Frame(),25)&&state.Entries.Count==8,"ninth active draft rejected");Check(state.Accept(1,Frame(2,0),26),"clear frees slot");Check(state.Accept(9,Frame(),27),"freed slot reusable");
var tombstones=new SharedPreviewSet();for(long i=1;i<=16;i++)tombstones.Accept(i,Frame(1,0),0);Check(!tombstones.Accept(17,Frame(),1),"tombstones bounded");tombstones.Expire(2,new HashSet<long>());Check(tombstones.Accept(17,Frame(),3),"offline tombstones reclaimed");
var cadence=new SharedPreviewCadence();Check(cadence.Due(0,true),"initial frame immediate");cadence.Sent(0);Check(!cadence.Due(0.49f,true)&&cadence.Due(0.5f,true),"edits bounded to two per second");Check(!cadence.Due(3.9f,false)&&cadence.Due(4,false),"unchanged heartbeat every four seconds");Check(cadence.Due(1,true),"stable draft does not delay next edit until heartbeat");cadence.Sent(1);Check(!cadence.Due(1.25f,true)&&cadence.Due(1.5f,true)&&cadence.Due(5,false),"timers reset after changes");
Console.WriteLine($"Shared preview checks passed: {checks}");
