<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>BobsPipes</AssemblyName><RootNamespace>BobsPipes</RootNamespace></PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>$(ManagedDir)/UnityEngine.ParticleSystemModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AnimationModule"><HintPath>$(ManagedDir)/UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
