<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AssemblyName>ChestSearch</AssemblyName><RootNamespace>ChestSearch</RootNamespace></PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine.UI"><HintPath>$(ManagedDir)/UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(ManagedDir)/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
